### PR TITLE
fix: correct isIosSafari logic to handle Facebook webview

### PR DESCRIPTION
**Pull request by golmansax**
Apologies for the delay on this one.  Fixes https://github.com/braintree/browser-detection/issues/26.

Let me know if there's anything I need to change or feel free to take over the PR.

### CODE REVIEW

**Review by crookedneighbor — APPROVED** [review]

**Review by sshropshire — APPROVED** [review]

**Comment by golmansax** [comment]
@crookedneighbor @sshropshire Could we get this merged and a version bumped?  Our product gets Facebook browser requests regularly, so it'd be nice to get this squared away.

Thank you!

**Comment by crookedneighbor** [comment]
Sorry for the delay. I'll look into getting this merged in early next week.

**Comment by crookedneighbor** [comment]
This is out in 1.12.1

**Comment by golmansax** [comment]
Thanks!  @crookedneighbor

**Pull request merged**
